### ISSUE TITLE
能不能去掉Chrome浏览器的依赖

### ISSUE THREAD

**Issue by bob-lytton** [luciusssss/PKUHoleCrawler#4]
我是用的FIrefox，希望这个爬虫能够支持不同的浏览器，看什么时候整一整？

**Comment by luciusssss** [comment]
可以使用urllib等包直接访问树洞的API（getlist, getcomment, getone, search等）从而十分方便地爬取内容，API具体可以查看static/js/flows_api.js。但这种爬虫会给服务器带来比较大的压力。
